#!/usr/env/bin ruby
# encoding: utf-8

# The Problem: https://projecteuler.net/problem=2
# ============================================================================
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
# ----------------------------------------------------------------------------
# Published on: Friday, 19th October 2001, 06:00 pm
# Solved by   : 274458 users.
# ----------------------------------------------------------------------------

require File.dirname(File.dirname(__FILE__)) + '/lib/base.rb'

module ProjectEuler
  class Solution2 < BaseSolution

    def solve
      # this method should start execution to return the answer to the problem.

      # uncomment the following, when you have solved this problem.
      # self.mark_as_solved

      # start writing your code now..
    end
  end
end
