#!/usr/env/bin ruby
# encoding: utf-8

# The Problem: https://projecteuler.net/problem=12
# ============================================================================
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
# first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
#  1: 1 3: 1,3 6: 1,2,3,610: 1,2,5,1015: 1,3,5,1521: 1,3,7,2128: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred
# divisors?
# ----------------------------------------------------------------------------
# Published on: Friday, 8th March 2002, 06:00 pm
# Solved by   : 91656 users.
# ----------------------------------------------------------------------------

require File.dirname(File.dirname(__FILE__)) + '/lib/base.rb'

module ProjectEuler
  class Solution12 < BaseSolution

    def solve
      # this method should start execution to return the answer to the problem.

      # uncomment the following, when you have solved this problem.
      # self.mark_as_solved

      # start writing your code now..
    end
  end
end
